name: iteo
favicon: null
layout_spectrum: 0.9968088769819587
typography_spectrum: 0.4199444828554988
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.740765530616045
  lightness: 0.8952530242968351
  saturation: 0.5326767021324486
  rhythmicContrast: 0.26958686555735767
purpose: []
