name: iteo
favicon: null
layout_spectrum: 0.6686
typography_spectrum: 0.30636
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#48dfc6'
    - '#40c1e6'
    - '#64cef7'
    - '#1f917c'
    - '#40a2f5'
  brandStrength: 0.75
  lightness: 0.8952530242968351
  saturation: 0.5326767021324486
  rhythmicContrast: 0.26958686555735767
purpose: []
